### ISSUE TITLE
Random Crash -Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!

### ISSUE THREAD

**Issue by rylandtikes** [rylandtikes/cs598-project#1]
ENVIRONMENT:
  Found when training on AWS AMI
  
  Deep Learning AMI GPU TensorFlow 2.12.0 (Ubuntu 20.04) 20230324
  g4dn.xlarge
  
  numpy==1.19.5
  pandas==1.1.5
  scikit_learn==1.2.2
  scipy==1.5.4
  tensorflow==2.6.2
  torch==1.10.2
  tqdm==4.64.1
  
  (cs598-project-py36) ubuntu@ip-172-31-34-6:~/cs598-project$ nvidia-smi
  Sun Apr  9 21:27:47 2023       
  +-----------------------------------------------------------------------------+
  | NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
  |-------------------------------+----------------------+----------------------+
  | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
  | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
  |                               |                      |               MIG M. |
  |===============================+======================+======================|
  |   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
  | N/A   40C    P0    61W /  70W |   2071MiB / 15360MiB |     84%      Default |
  |                               |                      |                  N/A |
  +-------------------------------+----------------------+----------------------+
                                                                                 
  +-----------------------------------------------------------------------------+
  | Processes:                                                                  |
  |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
  |        ID   ID                                                   Usage      |
  |=============================================================================|
  |    0   N/A  N/A      2156      C   python3                          2066MiB |
  +-----------------------------------------------------------------------------+

Error:
  Traceback (most recent call last):                                                                                                                 
    File "/home/ubuntu/cs598-project/train.py", line 111, in <module>
      main()
    File "/home/ubuntu/cs598-project/train.py", line 94, in main
      loss, kld, bce = train(batch_data, model, optimizer, criterion, args.lbd, 5)
    File "/home/ubuntu/cs598-project/utils.py", line 20, in train
      logits, kld = model(input)
    File "/home/ubuntu/anaconda3/envs/cs598-project-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/ubuntu/anaconda3/envs/cs598-project-py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
      return self.module(*inputs[0], **kwargs[0])
    File "/home/ubuntu/anaconda3/envs/cs598-project-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/ubuntu/cs598-project/model.py", line 211, in forward
      outputs = [self.encoder_decoder(data[i, :]) for i in range(batch_size)]
    File "/home/ubuntu/cs598-project/model.py", line 211, in <listcomp>
      outputs = [self.encoder_decoder(data[i, :]) for i in range(batch_size)]
    File "/home/ubuntu/cs598-project/model.py", line 191, in encoder_decoder
      h_prime = attn(input_edges, h_prime)
    File "/home/ubuntu/anaconda3/envs/cs598-project-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/ubuntu/cs598-project/model.py", line 107, in forward
      h_prime = torch.cat([self.attention(l, a, N, data, edge) for l, a in zip(self.W, self.a)], dim=1)
    File "/home/ubuntu/cs598-project/model.py", line 107, in <listcomp>
      h_prime = torch.cat([self.attention(l, a, N, data, edge) for l, a in zip(self.W, self.a)], dim=1)
    File "/home/ubuntu/cs598-project/model.py", line 87, in attention
      edge_e = torch.sparse_coo_tensor(edge, edge_e, torch.Size([N, N]))
  RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument values in method wrapper___sparse_coo_tensor_with_dims_and_tensors)

**Comment by rylandtikes** [comment]
Issue also seen on different machine.

[epoch:9] loss: 3.0106, bce: 2.9967, kld: 0.0140:  26%|█████████████████████                                                            | 1000/3845 [05:02<14:14,  3.33it/s]epoch:9 AUPRC:0.347712; loss: 3.0293, bce: 3.0152, kld: 0.0141
Traceback (most recent call last):                                                                                                                                          
  File "/home/rtikes/cs598-project/train.py", line 116, in <module>
    main()
  File "/home/rtikes/cs598-project/train.py", line 99, in main
    loss, kld, bce = train(batch_data, model, optimizer, criterion, args.lbd, 5)
  File "/home/rtikes/cs598-project/utils.py", line 22, in train
    logits, kld = model(input)
  File "/home/rtikes/anaconda3/envs/cs598-project-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rtikes/anaconda3/envs/cs598-project-py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/rtikes/anaconda3/envs/cs598-project-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rtikes/cs598-project/model.py", line 212, in forward
    outputs = [self.encoder_decoder(data[i, :]) for i in range(batch_size)]
  File "/home/rtikes/cs598-project/model.py", line 212, in <listcomp>
    outputs = [self.encoder_decoder(data[i, :]) for i in range(batch_size)]
  File "/home/rtikes/cs598-project/model.py", line 192, in encoder_decoder
    h_prime = attn(input_edges, h_prime)
  File "/home/rtikes/anaconda3/envs/cs598-project-py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rtikes/cs598-project/model.py", line 108, in forward
    h_prime = torch.cat([self.attention(l, a, N, data, edge) for l, a in zip(self.W, self.a)], dim=1)
  File "/home/rtikes/cs598-project/model.py", line 108, in <listcomp>
    h_prime = torch.cat([self.attention(l, a, N, data, edge) for l, a in zip(self.W, self.a)], dim=1)
  File "/home/rtikes/cs598-project/model.py", line 88, in attention
    edge_e = torch.sparse_coo_tensor(edge, edge_e, torch.Size([N, N]))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument values in method wrapper___sparse_coo_tensor_with_dims_and_tensors)
(cs598-project-py36) rtikes@ml-workstation:~/cs598-project$ nvidia-smi
Sun Apr  9 17:03:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:02:00.0  On |                  N/A |
|  0%   56C    P0    28W / 200W |    204MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1630      G   /usr/lib/xorg/Xorg                124MiB |
|    0   N/A  N/A      1792      G   /usr/bin/gnome-shell               37MiB |
|    0   N/A  N/A      6445      G   ...984690645908668607,131072       38MiB |
+-----------------------------------------------------------------------------+

**Comment by rylandtikes** [comment]
Issue appears to be resolved with https://github.com/rylandtikes/cs598-project/pull/8 . Will leave issue open a little longer to make sure it does not reoccur.

**Comment by rylandtikes** [comment]
Confirmed the issue is resolve now.
